# Generated by Django 2.1 on 2018-08-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timesmap']},
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
